<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip"
%>
# default: <%= std_opts %> features
default: --format pretty --strict --tags ~@wip #modified by jamis
current: --format pretty --strict --tags @current
#wip: --tags @wip:3 --wip features
wip: --tags @wip --wip features #modified by jamis
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip

# I like this one

# call these above by >> cucumber -p current

# TODO. Rethink the profiles. Having pretty all the time could be annoying when you have a lot of tests...